config/routes.rb
Ihome::Application.routes.draw do
  resources :tasks

  resources :rooms

  resources :interiors

  resources :residences
  post 'residences/:id' => 'residences#set_active_residence', as: 'set_active_residence'

  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}

  root to: 'welcome#index'
  
  get 'home' => 'home#index'

end

app/models/interior.rb
class Interior
  include Mongoid::Document
  
  field :clean_by_room, :type => Boolean, :default => false
  field :bedrooms, :type => Integer
  field :bathrooms, :type => Integer
  field :garage, :type => Boolean
  
  embedded_in :residence
  embeds_many :rooms
  embeds_many :tasks
  
  def set_rooms
    rooms << rooms.new( name: "Master Bedroom", category: "bedroom" )
    for i in 0..(bedrooms - 2)
      rooms << rooms.new( name: "Bedroom", category: "bedroom" )
    end
    
    rooms << rooms.new( name: "Master Bathroom", category: "bathroom" )
    for i in 0..(bathrooms - 2)
      rooms << rooms.new( name: "Bathroom", category: "bathroom" )
    end
    
    rooms << rooms.new( name: "Kitchen", category: "kitchen" )
    rooms << rooms.new( name: "Living Room", category: "room" )
    rooms << rooms.new( name: "Family Room", category: "room" )
    rooms << rooms.new( name: "Dining Room", category: "room" )
        
    if garage
      rooms << rooms.new( name: "Garage", category: "garage" )
    end
  end
  
  def set_tasks
    self.tasks << [
      tasks.new( name: "Sweep" ),
      tasks.new( name: "Mop" ),
      tasks.new( name: "Dust" ),
      tasks.new( name: "Vacuum" ),
      tasks.new( name: "Clean Dishes" ),
      tasks.new( name: "Wipe Counters" ),
      tasks.new( name: "Clean Oven" ),
      tasks.new( name: "Clean Refrigerator" ),
      tasks.new( name: "Clean Stovetop" ),
      tasks.new( name: "Clean Microwave" ),
      tasks.new( name: "Clean Freezer" ),
      tasks.new( name: "Clean Sink" ),
      tasks.new( name: "Clean Toilet" ),
      tasks.new( name: "Clean Bathtub" ),
      tasks.new( name: "Clean Shower" ),
      tasks.new( name: "Clean Cabinets" ),
      tasks.new( name: "Clean Refrigerator Coils" ),
      tasks.new( name: "Replace Furnace Filter" ),
      tasks.new( name: "Check Smoke Detector" )
    ]
  end
end

app/controllers/interiors_controller.rb
class InteriorsController < AuthenticatedController
  before_action :set_interior, only: [:show, :edit, :update, :destroy]

  # GET /interiors
  # GET /interiors.json
  def index
    #@residence = current_user.residences.find(params[:id])
    @interior = current_residence.interior
  end

  # GET /interiors/1
  # GET /interiors/1.json
  def show
  end

  # GET /interiors/new
  def new
    @interior = Interior.new
  end

  # GET /interiors/1/edit
  def edit
  end

  # POST /interiors
  # POST /interiors.json
  def create
    @interior = Interior.new(interior_params)
    current_residence.interior = @interior
    current_residence.interior.set_rooms
    current_residence.interior.set_tasks
    respond_to do |format|
      if @interior.save
        format.html { redirect_to @interior, notice: 'Interior was successfully created.' }
        format.json { render action: 'show', status: :created, location: @interior }
      else
        format.html { render action: 'new' }
        format.json { render json: @interior.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interiors/1
  # PATCH/PUT /interiors/1.json
  def update
    respond_to do |format|
      if @interior.update_attributes(interior_params)
        format.html { redirect_to @interior, notice: 'Interior was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @interior.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interiors/1
  # DELETE /interiors/1.json
  def destroy
    @interior.destroy
    respond_to do |format|
      format.html { redirect_to interiors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interior
      @interior = current_residence.interior
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interior_params
      params.require(:interior).permit(:clean_by_room, :bedrooms, :bathrooms, :garage)
    end
end

app/helpers/interiors_helper.rb
module InteriorsHelper
end

app/views/interiors/_form.html.erb
<%= form_for(@interior) do |f| %>
  <% if @interior.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interior.errors.count, "error") %> prohibited this interior from being saved:</h2>

      <ul>
      <% @interior.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="responses">
    <div class="field">
      <p>Do you want to get reminders to clean by room or by task?</p>
      <%= f.radio_button :clean_by_room, "false" %>
      <%= f.label :clean_by_room, "Task" %>
      <%= f.radio_button :clean_by_room, "true" %>
      <%= f.label :clean_by_room, "Room" %>
    </div>
    <div class="field">
      <%= f.label :bedrooms, "How many bedrooms are in this residence?" %>
      <%= f.text_field :bedrooms %>
    </div>
    <div class="field">
      <%= f.label :bathrooms, "How many bathrooms are in this residence?" %>
      <%= f.text_field :bathrooms %>
    </div>
    <div class="field">
      <p>Do you have a garage?</p>
      <%= f.radio_button :garage, "true" %>
      <%= f.label :garage, "Yes" %>
      <%= f.radio_button :garage, "false" %>
      <%= f.label :garage, "No" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/interiors/_set_tasks_for_rooms.html.erb
<%= form_for(@interior) do |f| %>
  <% if @interior.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interior.errors.count, "error") %> prohibited this interior from being saved:</h2>

      <ul>
      <% @interior.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="responses">
    <div class="field">
      <p>Do you want to get reminders to clean by room or by task?</p>
      <%= f.radio_button :clean_by_room, "false" %>
      <%= f.label :clean_by_room, "Task" %>
      <%= f.radio_button :clean_by_room, "true" %>
      <%= f.label :clean_by_room, "Room" %>
    </div>
    <div class="field">
      <%= f.label :bedrooms, "How many bedrooms are in this residence?" %>
      <%= f.text_field :bedrooms %>
    </div>
    <div class="field">
      <%= f.label :bathrooms, "How many bathrooms are in this residence?" %>
      <%= f.text_field :bathrooms %>
    </div>
    <div class="field">
      <p>Do you have a garage?</p>
      <%= f.radio_button :garage, "true" %>
      <%= f.label :garage, "Yes" %>
      <%= f.radio_button :garage, "false" %>
      <%= f.label :garage, "No" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/interiors/edit.html.erb
<h1>Editing interior</h1>

<%= render 'form' %>

<%= link_to 'Show', @interior %> |
<%= link_to 'Back', interiors_path %>

app/views/interiors/index.html.erb
<h1>Listing interiors</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% if @interior %>
    <tr>
      <td><%= current_residence.name %></td>
      <td><%= link_to 'Show', current_residence.interior %></td>
      <td><%= link_to 'Edit', edit_interior_path(current_residence.interior) %></td>
      <td><%= link_to 'Destroy', current_residence.interior, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<% unless @interior %>
  <%= link_to 'New Interior', new_interior_path %>
<% end %>
<%= link_to 'Back', residences_path %>

app/views/interiors/new.html.erb
<h1>New interior</h1>

<%= render 'form' %>

<%= link_to 'Back', interiors_path %>

app/views/interiors/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= current_residence.name %></h3>
<p>Clean By Room: <%= @interior.clean_by_room %></p>
<p>Bedrooms: <%= @interior.bedrooms %></p>
<p>Bathrooms: <%= @interior.bathrooms %></p>
<p>Garage: <%= @interior.garage %></p>

<%= link_to 'Edit', edit_interior_path(@interior) %> |
<%= link_to 'Back', interiors_path %> |
<%= link_to 'Rooms', rooms_path %> |
<%= link_to 'Tasks', tasks_path %>