config/routes.rb
Ihome::Application.routes.draw do
  resources :tasks

  resources :rooms

  resources :interiors

  resources :residences
  post 'residences/:id' => 'residences#set_active_residence', as: 'set_active_residence'

  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}

  root to: 'welcome#index'
  
  get 'home' => 'home#index'

end

app/models/residence.rb
class Residence
  include Mongoid::Document
  
  field :name, :type => String
  field :rent, :type => Boolean, :default => false
  field :cleaning_frequency, :type => Integer, :default => 3
  
  has_and_belongs_to_many :user
  embeds_one :interior
end

app/controllers/residences_controller.rb
class ResidencesController < AuthenticatedController
  before_action :set_residence, only: [:show, :edit, :update, :destroy]

  # GET /residences
  # GET /residences.json
  def index
    @residences = current_user.residences.all
  end

  # GET /residences/1
  # GET /residences/1.json
  def show
  end

  # GET /residences/new
  def new
    @residence = Residence.new
  end

  # GET /residences/1/edit
  def edit
  end

  # POST /residences
  # POST /residences.json
  def create
    @residence = Residence.new(residence_params)
    current_user.residences << @residence
    current_user.set_current_residence(@residence.id)

    respond_to do |format|
      if @residence.save
        format.html { redirect_to @residence, notice: 'Residence was successfully created.' }
        format.json { render action: 'show', status: :created, location: @residence }
      else
        format.html { render action: 'new' }
        format.json { render json: @residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residences/1
  # PATCH/PUT /residences/1.json
  def update
    respond_to do |format|
      if @residence.update_attributes(residence_params)
        current_user.save
        format.html { redirect_to @residence, notice: 'Residence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residences/1
  # DELETE /residences/1.json
  def destroy
    @residence.destroy
    respond_to do |format|
      format.html { redirect_to residences_url }
      format.json { head :no_content }
    end
  end
  
  def set_active_residence
    current_user.set_current_residence(params[:id])
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_residence
      @residence = Residence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def residence_params
      params.require(:residence).permit(:name, :rent, :cleaning_frequency)
    end
end

app/helpers/residences_helper.rb
module ResidencesHelper
end

app/views/residences/_form.html.erb
<%= form_for(@residence) do |f| %>
  <% if @residence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@residence.errors.count, "error") %> prohibited this residence from being saved:</h2>

      <ul>
      <% @residence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="responses">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <p>Do you rent?</p>
      <%= f.radio_button :rent, "true" %>
      <%= f.label :rent, "Yes" %>
      <%= f.radio_button :rent, "false" %>
      <%= f.label :rent, "No" %>
    </div>
    <div class="field">
      <p>How often do you want to clean?</p>
      <%= f.radio_button :cleaning_frequency, "1" %>
      <%= f.label :cleaning_frequency, "Very Infrequently" %>
      <%= f.radio_button :cleaning_frequency, "2" %>
      <%= f.label :cleaning_frequency, "Infrequently" %>
      <%= f.radio_button :cleaning_frequency, "3" %>
      <%= f.label :cleaning_frequency, "Normally" %>
      <%= f.radio_button :cleaning_frequency, "4" %>
      <%= f.label :cleaning_frequency, "Frequently" %>
      <%= f.radio_button :cleaning_frequency, "5" %>
      <%= f.label :cleaning_frequency, "Very Frequently" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/residences/edit.html.erb
<h1>Editing residence</h1>

<%= render 'form' %>

<%= link_to 'Show', @residence %> |
<%= link_to 'Back', residences_path %>

app/views/residences/index.html.erb
<h1>Listing residences</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @residences.each do |residence| %>
    <tr>
      <td><%= residence.name %></td>
      <td><%= link_to 'Show', residence %></td>
      <td><%= link_to 'Edit', edit_residence_path(residence) %></td>
      <td><%= link_to 'Destroy', residence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td>
        <% if current_residence.eql? residence %>
          <div>Active Residence</div>
        <% else %>
          <%= button_to 'Change To Active Residence', set_active_residence_path(residence.id) %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Residence', new_residence_path %>

app/views/residences/new.html.erb
<h1>New residence</h1>

<%= render 'form' %>

<%= link_to 'Back', residences_path %>

app/views/residences/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @residence.name %></h3>
<p>Rent: <%= @residence.rent %></p>
<p>Cleaning Frequency: <%= @residence.cleaning_frequency %></p>

<%= link_to 'Edit', edit_residence_path(@residence) %> |
<%= link_to 'Back', residences_path %> |
<% if current_residence.eql? @residence %>
  <%= link_to 'Interior', interiors_path %>
<% else %>
  <%= button_to 'Change To Active Residence', set_active_residence_path(@residence.id) %>
<% end %>